/*
 * Public profile settings. Add links here when your GitHub/Scholar pages are ready.
 * Keeping these in one place makes the template easy to personalize.
 */
window.PROFILE = {
  email: '17538311715@163.com',
  github: 'https://github.com/fc-new',
  scholar: '',
  // Resume supplied by the site owner; replace this PDF to update the download.
  cv: 'assets/chenyang-fu-cv.pdf'
};

window.I18N = {
  zh: {
    skip: '跳转到正文', navAbout: '简介', navResearch: '研究', navProjects: '项目', navHonors: '荣誉', navContact: '联系',
    heroEyebrow: '西安电子科技大学 · 本科生', heroDescription: '探索更高效的大语言模型智能体：从动态推理与上下文管理，到参数高效微调。', viewResearch: '探索我的研究', viewCV: '查看简历', location: '中国 · 西安', visualHeading: '更少的开销。<br>更有效的智能。', visualCaption: '围绕效率，连接三条研究线索', scrollHint: '继续了解',
    aboutTitle: '关于我', aboutAside: '从问题出发，在实践中探索。', aboutLead: '你好，我是付晨阳，西安电子科技大学大数据管理与应用专业本科生。', aboutBody: '我的研究兴趣集中于大语言模型智能体的效率问题：如何按需分配推理资源，如何保留真正有用的上下文，以及如何以更少的可训练参数适配模型。我参与了张宁豫老师指导的智能体研究，也在沈玉龙教授团队参与 CryptoLLM 的语料构建与后训练工作。', school: '西安电子科技大学', degree: '大数据管理与应用 · 本科', educationDate: '2023.09 — 至今', rankLabel: '专业排名', scholarshipLabel: '国家奖学金',
    researchTitle: '研究工作', researchAside: '三个问题，一条效率主线。', researchIntro: '从上下文、推理到参数更新，探索大语言模型系统的效率与适应能力。', schematic: '研究主题示意', tokenStatus: 'EMNLP · 已投稿', tokenRole: '共同第一作者', tokenDescription: '面向长时序交互中的上下文冗余与推理开销，通过缓存友好的上下文组织与动态管理，探索性能与成本的平衡。', contribution: '我的工作', tokenContribution: '优化会话前缀稳定性以提升 KV 缓存复用；对工具观测进行结构化精简与按需恢复；设计生命周期感知的滑动窗口上下文驱逐策略。', loraStatus: 'AAAI · 已投稿', loraRole: '学生第一作者', loraDescription: '面向差分隐私联邦学习，探索低参数 LoRA 适配方法，缓解双因子训练的噪声放大与通信开销问题。', loraContribution: '采用三因子低秩表示，仅训练中间矩阵 R；设计坐标变换潜空间映射协议；通过服务端周期性 SVD 重定向，让低秩子空间适应全局更新方向。', routerStatus: '软件学报 · 已投稿', routerRole: '第二作者', routerDescription: '面向多轮交互中的资源分配问题，让智能体根据任务特性动态调整推理与检索策略。', routerContribution: '负责 Trigger 模块的数据生成与 SFT 冷启动，使用 LLaMA-Factory 完成训练；基于 Alibaba ROLL 为 Trigger 与 Reason 模块开展 GRPO 强化学习训练。', projectPage: '项目主页',
    projectsTitle: '从研究到实践', projectsAside: '数据、训练，以及真实的问题。', cryptoRole: '算法实习生', cryptoSubtitle: '密码学领域大语言模型', cryptoDescription: '参与 CryptoCorpus 5B 级语料库构建，覆盖六类异构数据来源；基于 Qwen3-32B 进行指令微调、对话增强与强化学习，参与模型迭代至 V3.0。', cryptoTeam: '沈玉龙教授团队', droneRole: '核心成员 · 2025', droneTitle: '无人机射频识别', droneSubtitle: '陕西省大学生创新创业计划', droneDescription: '采集无人机图传信号，通过 STFT 构建时频谱图数据集；结合改进 AlexNet 与 YOLO，开展低空无人机信号识别。', opticalRole: '项目负责人 · 2025', opticalTitle: '光纤传感解调', opticalSubtitle: '西电腾飞科创计划', opticalDescription: '基于珐珀腔干涉原理构建含噪光谱数据集；设计均匀分光与滤波方案，结合轻量型 CNN 和注意力模型探索高精度解调。',
    honorsTitle: '沿途的积累', honorsIntro: '在学术训练与跨学科实践中，保持好奇，持续积累。', nationalScholarship: '连续两年国家奖学金', scholarshipNote: '本科阶段', mathAward: '全国大学生数学竞赛', provincialFirst: '省级一等奖', designAward: '中国大学生计算机设计大赛', designPrize: '省级二等奖 · 两项（含人工智能赛道）', mcmAward: '美国大学生数学建模竞赛', mcmPrize: '国际二等奖', cumcmAward: '全国大学生数学建模竞赛', outsourcingAward: '服务外包创新创业大赛', nationalThird: '国家三等奖',
    contactTitle: '从一次交流开始。', contactDescription: '欢迎交流智能体、上下文管理与高效微调相关的研究问题。', copyEmail: '复制邮箱', downloadCV: '简历 PDF ↗', footerNote: '保持好奇，认真求索。', backTop: '回到顶部 ↑', copied: '已复制邮箱', copyFailed: '请手动复制邮箱'
  },
  en: {
    skip: 'Skip to content', navAbout: 'About', navResearch: 'Research', navProjects: 'Projects', navHonors: 'Honors', navContact: 'Contact',
    heroEyebrow: 'Xidian University · Undergraduate', heroDescription: 'Exploring more efficient LLM agents—from dynamic reasoning and context management to parameter-efficient fine-tuning.', viewResearch: 'Explore my research', viewCV: 'View CV', location: 'Xi’an · China', visualHeading: 'Less overhead.<br>More useful intelligence.', visualCaption: 'Three lines of inquiry, one focus on efficiency', scrollHint: 'Discover more',
    aboutTitle: 'About me', aboutAside: 'Start with a problem. Learn by building.', aboutLead: 'Hi, I’m Chenyang Fu, an undergraduate studying Big Data Management and Application at Xidian University.', aboutBody: 'My research focuses on making large language model agents more efficient: allocating reasoning resources on demand, preserving useful context, and adapting models with fewer trainable parameters. I work on agent research with Prof. Ningyu Zhang and have also contributed to corpus construction and post-training for CryptoLLM in Prof. Yulong Shen’s team.', school: 'Xidian University', degree: 'Big Data Management and Application · Undergraduate', educationDate: 'Sep 2023 — present', rankLabel: 'Major rank', scholarshipLabel: 'National scholarships',
    researchTitle: 'Research', researchAside: 'Three questions. One line of efficiency.', researchIntro: 'From context and reasoning to parameter updates, I study efficiency and adaptation in LLM systems.', schematic: 'research sketch', tokenStatus: 'EMNLP · Submitted', tokenRole: 'Co-first author', tokenDescription: 'A study of cache-friendly context organization and dynamic management for long-horizon interactions, balancing capability with inference cost.', contribution: 'My contribution', tokenContribution: 'Stabilized session prefixes for higher KV-cache reuse; designed lossless, structured compression for tool observations; developed a lifecycle-aware sliding-window eviction strategy.', loraStatus: 'AAAI · Submitted', loraRole: 'Student first author', loraDescription: 'A low-parameter LoRA adaptation method for differentially private federated learning, targeting noise amplification and communication overhead.', loraContribution: 'Used a three-factor low-rank representation and trained only the middle matrix R; designed a coordinate-transformed latent-space protocol; introduced periodic server-side SVD redirection.', routerStatus: 'Journal of Software · Submitted', routerRole: 'Second author', routerDescription: 'A metacognitive router that dynamically adjusts reasoning and retrieval strategies according to the task at hand.', routerContribution: 'Built data and the SFT cold start for the Trigger module with LLaMA-Factory; trained Trigger and Reason with GRPO on Alibaba ROLL.', projectPage: 'Project page',
    projectsTitle: 'Research in practice', projectsAside: 'Data, training, and real problems.', cryptoRole: 'Algorithm intern', cryptoSubtitle: 'A large language model for cryptography', cryptoDescription: 'Contributed to the 5B-token CryptoCorpus across six heterogeneous sources; worked on instruction tuning, dialogue enhancement, and reinforcement learning with Qwen3-32B through V3.0.', cryptoTeam: 'Prof. Yulong Shen’s team', droneRole: 'Core member · 2025', droneTitle: 'RF drone detection', droneSubtitle: 'Shaanxi Student Innovation Program', droneDescription: 'Built a time-frequency dataset from drone video-link signals with STFT; trained improved AlexNet and YOLO models for low-altitude drone identification.', opticalRole: 'Project lead · 2025', opticalTitle: 'Fiber sensing demodulation', opticalSubtitle: 'Xidian Tengfei Innovation Program', opticalDescription: 'Built noisy spectral data from Fabry–Pérot interference; designed a uniform-splitting and filtering pipeline with a lightweight CNN and attention model.',
    honorsTitle: 'Along the way', honorsIntro: 'Staying curious through academic training and cross-disciplinary building.', nationalScholarship: 'Two consecutive National Scholarships', scholarshipNote: 'Undergraduate', mathAward: 'National College Mathematics Competition', provincialFirst: 'Provincial First Prize', designAward: 'China College Computer Design Competition', designPrize: 'Two Provincial Second Prizes, including AI track', mcmAward: 'MCM/ICM', mcmPrize: 'International Second Prize', cumcmAward: 'China Undergraduate Mathematical Contest in Modeling', outsourcingAward: 'Service Outsourcing Innovation & Entrepreneurship Competition', nationalThird: 'National Third Prize',
    contactTitle: 'Start with a conversation.', contactDescription: 'I’m happy to talk about agents, context management, and efficient fine-tuning.', copyEmail: 'Copy email', downloadCV: 'CV PDF ↗', footerNote: 'Stay curious. Keep building.', backTop: 'Back to top ↑', copied: 'Email copied', copyFailed: 'Please copy the email manually'
  }
};
